services:
  backend:
    build:
      context: ./backend  # Chemin vers le dossier backend (Express.js)
      dockerfile: Dockerfile
    container_name: express-backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://express_user:password@postgres:5432/cashsofttracker_db
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend  # Chemin vers le dossier frontend (React ou Next.js)
      dockerfile: Dockerfile
    container_name: react-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      NODE_ENV: development
      BROWSER: none  # Ajout pour désactiver l'ouverture automatique du navigateur

  postgres:
    image: postgres:14-alpine
    container_name: express-postgres
    environment:
      POSTGRES_USER: express_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cashsofttracker_db  # Nom de la base de données PostgreSQL
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: express-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app_network

  mailer:
    image: axllent/mailpit
    container_name: express-mailer
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
